name: DiscordRelay
version: '1.1.7'
main: com.jellypudding.discordRelay.DiscordRelay
api-version: '1.21'
description: "Relays messages between Minecraft and Discord."
author: AlphaAlex115
website: www.minecraftoffline.net
softdepend: [BedrockSupport, OfflineStats, ChromaTag]
loadbefore: [BedrockSupport, OfflineStats, SimpleLifesteal]
commands:
  discordrelay:
    description: "Manage the DiscordRelay plugin"
    usage: "/discordrelay <reload|send> [colour] [message]"
    permission: discordrelay.use
    permission-message: "You don't have permission to use DiscordRelay commands."
permissions:
  discordrelay.use:
    description: "Allows using DiscordRelay commands"
    default: op
  discordrelay.reload:
    description: "Allows reloading the DiscordRelay plugin"
    default: op
  discordrelay.send:
    description: "Allows sending formatted messages to Discord"
    default: op
