name: DiscordRelay
version: '1.1.4'
main: com.jellypudding.discordRelay.DiscordRelay
api-version: '1.21'
description: "Relays messages between Minecraft and Discord."
author: AlphaAlex115
website: www.minecraftoffline.net
softdepend: [BedrockSupport, OfflineStats, ChromaTag]
loadbefore: [BedrockSupport, OfflineStats]
commands:
  discordrelay:
    description: "Manage the DiscordRelay plugin"
    usage: "/discordrelay reload"
    permission: discordrelay.reload
    permission-message: "You don't have permission to reload DiscordRelay."
permissions:
  discordrelay.reload:
    description: Allows reloading the DiscordRelay plugin
    default: op